{% set name = "arraykit" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraykit-{{ version }}.tar.gz
  sha256: 687b2e0031607bb5f65642e6276416667da4e2abe968beba312cd2a9721cf11f

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy >=1.19.5
  run:
    - python
    - numpy >=1.19.5

test:
  imports:
    - arraykit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/arraykit
  summary: Array utilities for StaticFrame
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
