{% set name = "arraykit" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraykit-{{ version }}.tar.gz
  sha256: 53553fc86ac22606b47cd46a2e85b1200e11621ccce204988330e1ae4fd641c2

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - numpy >=1.16.5
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - arraykit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/InvestmentSystems/arraykit
  summary: Array utilities for StaticFrame
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flexatone
    - brandtbucher
    - chaburkland
