{% set name = "arraykit" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraykit-{{ version }}.tar.gz
  sha256: 2b4d65ebd51a4329d67ddc3dba3f7a17473dba09f2a96754aaeb5f8926700921

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy ==1.18.5  # [py==37]
    - numpy ==1.18.5  # [py==38]
    - numpy >=1.18.5  # [py>=39]
  run:
    - python
    - numpy ==1.18.5  # [py==37]
    - numpy ==1.18.5  # [py==38]
    - numpy >=1.18.5  # [py>=39]

test:
  imports:
    - arraykit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/static-frame/arraykit
  summary: Array utilities for StaticFrame
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - flexatone
    - chaburkland
